namespace DotnetPromptToolkit.Keys;

/// <summary>
/// Mirrors the prompt_toolkit.keys.Keys enumeration. Each value matches the
/// upstream string identifier so cross-language parity is verifiable.
/// </summary>
public enum Keys
{
    Escape,
    ControlAt,         // c-@
    ControlA,
    ControlB,
    ControlC,
    ControlD,
    ControlE,
    ControlF,
    ControlG,
    ControlH,
    ControlI,
    ControlJ,
    ControlK,
    ControlL,
    ControlM,
    ControlN,
    ControlO,
    ControlP,
    ControlQ,
    ControlR,
    ControlS,
    ControlT,
    ControlU,
    ControlV,
    ControlW,
    ControlX,
    ControlY,
    ControlZ,
    ControlBackslash,
    ControlSquareClose,
    ControlCircumflex,
    ControlUnderscore,
    Left,
    Right,
    Up,
    Down,
    Home,
    End,
    Insert,
    Delete,
    PageUp,
    PageDown,
    BackTab,
    Tab,
    Enter,
    Backspace,
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24,
    Space,
    Any,
    Vt100MouseEvent,
    WindowsMouseEvent,
    BracketedPaste,
    SIGINT,
    Ignore,
    CPRResponse,
    None
}

/// <summary>String identifiers matching the upstream Keys enum values.</summary>
public static class KeyNames
{
    public static string Name(Keys key) => key switch
    {
        Keys.ControlAt => "c-@",
        Keys.ControlA => "c-a",
        Keys.ControlB => "c-b",
        Keys.ControlC => "c-c",
        Keys.ControlD => "c-d",
        Keys.ControlE => "c-e",
        Keys.ControlF => "c-f",
        Keys.ControlG => "c-g",
        Keys.ControlH => "c-h",
        Keys.ControlI => "c-i",
        Keys.ControlJ => "c-j",
        Keys.ControlK => "c-k",
        Keys.ControlL => "c-l",
        Keys.ControlM => "c-m",
        Keys.ControlN => "c-n",
        Keys.ControlO => "c-o",
        Keys.ControlP => "c-p",
        Keys.ControlQ => "c-q",
        Keys.ControlR => "c-r",
        Keys.ControlS => "c-s",
        Keys.ControlT => "c-t",
        Keys.ControlU => "c-u",
        Keys.ControlV => "c-v",
        Keys.ControlW => "c-w",
        Keys.ControlX => "c-x",
        Keys.ControlY => "c-y",
        Keys.ControlZ => "c-z",
        Keys.ControlBackslash => "c-\\",
        Keys.ControlSquareClose => "c-]",
        Keys.ControlCircumflex => "c-^",
        Keys.ControlUnderscore => "c-_",
        Keys.Left => "left",
        Keys.Right => "right",
        Keys.Up => "up",
        Keys.Down => "down",
        Keys.Home => "home",
        Keys.End => "end",
        Keys.Insert => "insert",
        Keys.Delete => "delete",
        Keys.PageUp => "pageup",
        Keys.PageDown => "pagedown",
        Keys.BackTab => "s-tab",
        Keys.Tab => "tab",
        Keys.Enter => "enter",
        Keys.Backspace => "backspace",
        Keys.Escape => "escape",
        Keys.Space => "space",
        Keys.Any => "<any>",
        Keys.Vt100MouseEvent => "vt100-mouse-event",
        Keys.WindowsMouseEvent => "windows-mouse-event",
        Keys.BracketedPaste => "bracketed-paste",
        Keys.SIGINT => "sigint",
        Keys.Ignore => "ignore",
        Keys.CPRResponse => "cpr-response",
        Keys.None => "none",
        _ => key.ToString().ToLowerInvariant()
    };

    public static IReadOnlyList<Keys> All { get; } = Enum.GetValues<Keys>();
}
